manifest-version = 1

[component]
name = "example-ts-component"
version = "1.0.0"
category = "data-collection"
subcategory = "analytics"
description = "Example TypeScript component for data collection"
documentation = "https://github.com/edgee-cloud/example-ts-component"
repository = "https://github.com/edgee-cloud/example-ts-component"
language = "TypeScript"
wit-world-version = "0.5.0"

[component.build]
command = "npm install && npm run generate && npm run build"
output_path = "./example-ts-component.wasm"

[component.settings.example]
title = "Example Config Field"
type = "string"
