manifest-version = 1

[component]
name = "example-ts-edge-function-component"
version = "1.0.0"
category = "edge-function"
subcategory = "wasm-function"
description = "Example TypeScript component for edge function"
documentation = "https://github.com/edgee-cloud/example-ts-component"
repository = "https://github.com/edgee-cloud/example-ts-component"
language = "TypeScript"
wit-version = "1.0.0"

[component.build]
command = "npm install && npm run generate && npm run build"
output_path = "./example-ts-edge-function-component.wasm"

[component.settings.example]
title = "Example Config Field"
type = "string"
