manifest-version = 1

[component]
name = "example-ts-data-collection-component"
version = "1.0.0"
category = "data-collection"
subcategory = "analytics"
description = '''
## Overview

Describe **what this component does** and why it exists.

---

## ✨ Key Features & Benefits

### Features

- **Feature 1**: Quick feature description.
- **Feature 2**: Quick feature description.

### Benefits

- **Benefit 1**: Quick benefit description.
- **Benefit 2**: Quick benefit description.

---

## 🚀️ Use Cases

- **Use Case 1**: Quick use case description.
- **Use Case 2**: Quick use case description.

---

Additional resources: [Resource example](https://your-resource-link.com)
'''
documentation = "https://github.com/edgee-cloud/example-ts-component"
repository = "https://github.com/edgee-cloud/example-ts-component"
language = "TypeScript"
wit-version = "1.0.0"

[component.build]
command = "npm install && npm run generate && npm run build"
output_path = "./example-ts-component.wasm"

[component.settings.example]
title = "Example Config Field"
type = "string"
